### ISSUE TITLE
是否有兴趣在WinUI3上开发一个弹幕渲染引擎？

### ISSUE THREAD

**Issue by BlameTwo** [cotaku/DanmakuFrostMaster#1]
我看到这个项目只在UWP上有，请问是否有兴趣迁移到WinUI3呢？

**Comment by cotaku** [comment]
CanvasAnimatedControl控件暂时在WinUI3上不支持，参见：https://microsoft.github.io/Win2D/WinUI3/html/T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasAnimatedControl.htm
而且目前整个Win2D都还不完全支持WinUI3（WinUI2貌似可以）

**Comment by BlameTwo** [comment]
那只能等待了，我尝试移植了一下必须引用UWP相关的包😢

**Comment by BlameTwo** [comment]
https://github.com/SunburstApps/Win2D.WinUI

我在这里找到一个第三方的使用WinUI实现的Win2D

**Comment by cotaku** [comment]
毕竟WinUI也是开源的，移植一下说不定也没什么问题。不过如果有了Win2D on WinUI3的话，似乎也没什么移植工作需要做了，毕竟这个项目大部分代码都是UI无关的，前台只要有CanvasAnimatedControl应该就能直接跑。

**Comment by Sanlorng** [comment]
> 毕竟WinUI也是开源的，移植一下说不定也没什么问题。不过如果有了Win2D on WinUI3的话，似乎也没什么移植工作需要做了，毕竟这个项目大部分代码都是UI无关的，前台只要有CanvasAnimatedControl应该就能直接跑。

试了一下，直接用.Net升级助手迁移，然后再稍微改一下项目文件，就跑起来了，不需要额外的破坏性修改，具体看我的https://github.com/Sanlorng/DanmakuFrostMaster/tree/winui
![image](https://github.com/user-attachments/assets/8b73a37d-cf72-44ee-8209-45c1344dc08d)

**Comment by cotaku** [comment]
> 接用.Net升级助手

手动点赞

**Comment by JasonWei512** [comment]
题外话，如果你是为了用新 .NET 才迁移到 WinUI 3 的话，UWP 要支持 .NET 9 了：

https://devblogs.microsoft.com/ifdef-windows/preview-uwp-support-for-dotnet-9-native-aot/
